-- 008_add_customer_name_columns.up.sql
-- Add missing customer name and address columns required by TPC-C standard

ALTER TABLE customer 
    ADD COLUMN IF NOT EXISTS c_first VARCHAR(16) NOT NULL DEFAULT 'FirstName',
    ADD COLUMN IF NOT EXISTS c_middle CHAR(2) NOT NULL DEFAULT 'OE',
    ADD COLUMN IF NOT EXISTS c_last VARCHAR(16) NOT NULL DEFAULT 'LastName',
    ADD COLUMN IF NOT EXISTS c_street_1 VARCHAR(20) NOT NULL DEFAULT 'Street1',
    ADD COLUMN IF NOT EXISTS c_street_2 VARCHAR(20) NOT NULL DEFAULT 'Street2',
    ADD COLUMN IF NOT EXISTS c_city VARCHAR(20) NOT NULL DEFAULT 'City',
    ADD COLUMN IF NOT EXISTS c_state CHAR(2) NOT NULL DEFAULT 'ST',
    ADD COLUMN IF NOT EXISTS c_zip CHAR(9) NOT NULL DEFAULT '00000-000',
    ADD COLUMN IF NOT EXISTS c_phone CHAR(16) NOT NULL DEFAULT '1234567890123456',
    ADD COLUMN IF NOT EXISTS c_since TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS c_credit CHAR(2) NOT NULL DEFAULT 'GC',
    ADD COLUMN IF NOT EXISTS c_credit_lim DECIMAL(12,2) NOT NULL DEFAULT 50000.00,
    ADD COLUMN IF NOT EXISTS c_discount DECIMAL(4,4) NOT NULL DEFAULT 0.0000,
    ADD COLUMN IF NOT EXISTS c_data TEXT NOT NULL DEFAULT 'customer data';
