# E-Commerce Mixed Workload Configuration for EPAS v16
# This workload simulates a modern e-commerce platform with:
# - 75% read operations (product searches, user queries, analytics)
# - 25% write operations (orders, reviews, inventory updates, stock control)
# - Real-time stock level management with automatic reordering
# NOTE: E-commerce workloads are now provided by the ecommerce_plugin

database:
  type: postgres
  host: "p-rzjaqzb0yn-rw-external-31683a08ddd89515.elb.us-east-1.amazonaws.com"
  # host: "localhost"
  port: 5432
  dbname: "edb_admin"
  username: "edb_admin"
  password: "mattdemo123!"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
  
  # Specific plugin files to load (optional)
  files:
    - "./build/plugins/ecommerce_plugin.so"
  
  # Automatically load all plugins found in search paths
  auto_load: true

workload: "ecommerce_mixed"
scale: 1000

# Regular benchmark settings (ignored in progressive mode)
duration: "4h"
workers: 10
connections: 20
summary_interval: "5m"  # Show progress every 5 minutes

# Progressive scaling configuration - 4 hour test with 8 bands of 30 minutes each
progressive:
  enabled: true
  strategy: "linear"              # Linear scaling from 20 to 150 connections
  min_workers: 10                 # Start with 10 workers
  max_workers: 75                 # Scale up to 75 workers
  min_connections: 20             # Start with 20 connections
  max_connections: 150            # Scale up to 150 connections
  test_duration: "30m"            # Run each band for 30 minutes
  warmup_duration: "2m"           # Warmup time per band
  cooldown_duration: "1m"         # Cooldown time between bands
  bands: 8                        # Number of test configurations (4 hours total)
  enable_analysis: true           # Enable mathematical analysis

# Optional settings for detailed configuration
workload_config:
  # E-commerce specific settings
  inventory_threshold: 100        # Minimum stock level before reordering
  order_batch_size: 50           # Orders processed per batch
  enable_recommendations: true    # Enable product recommendation features
  # Note: pgvector features may be limited on EPAS v16
  enable_vector_search: false    # Disable pgvector-based features for v16 compatibility
