# Real-World E-Commerce Workload Configuration for EPAS v16
# This configuration simulates realistic e-commerce database usage patterns
# with complex queries, mixed OLTP/OLAP workloads, and comprehensive indexing
# Optimized for EPAS v16 compatibility

database:
  type: postgres
  host: "p-rzjaqzb0yn-rw-external-31683a08ddd89515.elb.us-east-1.amazonaws.com"
  port: 5432
  dbname: "edb_admin"
  username: "edb_admin"
  password: "mattdemo123!"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files:
    - "./build/plugins/realworld_plugin.so"
  
  # Automatically load all plugins found in search paths
  auto_load: true

# Load settings
workload: "realworld"     # Real-world e-commerce workload
scale: 1200               # Number of users to generate (conservative for v16)
duration: "90s"           # Duration of the test (1.5 minutes)
workers: 10               # Number of concurrent worker threads (conservative)
connections: 20           # Max connections in pool
summary_interval: "15s"   # Show progress every 15 seconds

# Workload-specific settings (these will be parsed by the workload itself)
workload_config:
  mode: "mixed"           # Options: read, write, mixed, oltp, analytics
  
  # Data scaling parameters (conservative for v16)
  data_scale:
    users: 12000          # Number of users to generate
    products: 6000        # Number of products to generate
    orders: 60000         # Number of orders to generate
    reviews: 30000        # Number of reviews to generate
    sessions: 120000      # Number of user sessions to generate
    analytics_events: 600000  # Number of analytics events to generate

  # Workload distribution (percentages should sum to 100)
  workload_mix:
    # Mixed mode distribution
    mixed:
      read_operations: 75
      write_operations: 20
      analytics_operations: 5    # Reduced analytics for v16
      
    # OLTP mode distribution
    oltp:
      transactional_operations: 90  # Higher focus on transactions
      reporting_operations: 8
      maintenance_operations: 2
      
    # Analytics mode distribution (simplified for v16)
    analytics:
      aggregation_queries: 50
      reporting_queries: 40
      data_mining_queries: 10      # Reduced complexity

  # Performance and behavior settings (conservative for v16)
  performance:
    batch_size: 50              # Smaller batch size for stability
    cache_hit_ratio: 0.80      # Slightly lower cache hit ratio
    think_time_ms: 100         # Higher think time for v16
    connection_pool_size: 20   # Conservative connection pool size
    
  # Feature flags for EPAS v16 (conservative settings)
  features:
    enable_partitioning: false     # Disable advanced partitioning
    enable_parallel_queries: false # Disable parallel queries for stability
    enable_advanced_indexes: false # Stick to basic indexes
    enable_materialized_views: true # Keep materialized views (supported in v16)
