# IMDB Mixed Workload Configuration for EPAS v16
# Very intensive mixed read and write operations (70% read, 30% write)
# NOTE: IMDB workloads are now provided by the imdb_plugin

database:
  type: postgres
  host: "p-rzjaqzb0yn-rw-external-31683a08ddd89515.elb.us-east-1.amazonaws.com"
  port: 5432
  dbname: "edb_admin"
  username: "edb_admin"
  password: "mattdemo123!"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files: 
    - "./build/plugins/imdb_plugin.so"
  
  # Automatically load all plugins found in search paths
  auto_load: true

# Data loading configuration for IMDB workload
# Options:
# - mode: "generate" (default) - Generate synthetic data using stormdb
# - mode: "dump" - Load data from a PostgreSQL dump file (pg_restore)
# - mode: "sql" - Load data from an SQL script file
data_loading:
  mode: "generate"              # Can be: generate, dump, sql
  # filepath: "/path/to/imdb.dump"    # Required for dump/sql modes
  # filepath: "/path/to/imdb.sql"     # Required for dump/sql modes

workload: "imdb_mixed"          # Mixed intensive operations (70% read, 30% write)
scale: 4000                     # Slightly smaller dataset for v16
workers: 10                     # Conservative for EPAS v16
duration: "60s"                 # Run for 1 minute
connections: 20                 # Connection pool size
summary_interval: "15s"         # Show progress every 15 seconds

# IMDB workload specific configuration
workload_config:
  # Complex query patterns (conservative settings for v16)
  enable_analytics: true        # Enable analytical queries on movie data
  enable_search: true          # Enable text search queries
  enable_aggregations: true    # Enable complex aggregations
  batch_insert_size: 500      # Smaller batch size for v16 stability
