# IMDB Mixed Workload Configuration for EPAS v17
# Very intensive mixed read and write operations (70% read, 30% write)
# NOTE: IMDB workloads are now provided by the imdb_plugin

database:
  type: postgres
  host: "p-5z2mcdtt4g-rw-external-4742739c702557c6.elb.us-east-1.amazonaws.com"
  port: 5432
  dbname: "edb_admin"
  username: "edb_admin"
  password: "mattdemo123!"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
  
  # Specific plugin files to load (optional)
  files: 
    - "./build/plugins/imdb_plugin.so"
  
  # Automatically load all plugins found in search paths
  auto_load: true

# Data loading configuration for IMDB workload
# Options:
# - mode: "generate" (default) - Generate synthetic data using stormdb
# - mode: "dump" - Load data from a PostgreSQL dump file (pg_restore)
# - mode: "sql" - Load data from an SQL script file
data_loading:
  mode: "generate"              # Can be: generate, dump, sql
  # filepath: "/path/to/imdb.dump"    # Required for dump/sql modes
  # filepath: "/path/to/imdb.sql"     # Required for dump/sql modes

workload: "imdb_mixed"          # Mixed intensive operations (70% read, 30% write)
scale: 5000                     # Medium dataset for balanced testing

# Regular benchmark settings (ignored in progressive mode)
duration: "4h"                 # Total test duration
workers: 12                     # Increased for 4GB/8GB system
connections: 25                 # Connection pool size
summary_interval: "5m"         # Show progress every 5 minutes

# Progressive scaling configuration - 4 hour test with 8 bands of 30 minutes each
progressive:
  enabled: true
  strategy: "linear"              # Linear scaling from 20 to 150 connections
  min_workers: 12                 # Start with 12 workers
  max_workers: 85                 # Scale up to 85 workers
  min_connections: 20             # Start with 20 connections
  max_connections: 150            # Scale up to 150 connections
  test_duration: "30m"            # Run each band for 30 minutes
  warmup_duration: "2m"           # Warmup time per band
  cooldown_duration: "1m"         # Cooldown time between bands
  bands: 8                        # Number of test configurations (4 hours total)
  enable_analysis: true           # Enable mathematical analysis

# IMDB workload specific configuration
workload_config:
  # Complex query patterns
  enable_analytics: true        # Enable analytical queries on movie data
  enable_search: true          # Enable text search queries
  enable_aggregations: true    # Enable complex aggregations
  batch_insert_size: 1000     # Batch size for bulk insert operations
