# E-Commerce Mixed Workload Configuration for EPAS v16
# This workload simulates a modern e-commerce platform with:
# - 75% read operations (product searches, user queries, analytics)
# - 25% write operations (orders, reviews, inventory updates, stock control)
# - Real-time stock level management with automatic reordering
# NOTE: E-commerce workloads are now provided by the ecommerce_plugin

database:
  type: postgres
  host: "p-rzjaqzb0yn-rw-external-31683a08ddd89515.elb.us-east-1.amazonaws.com"
  port: 5432
  dbname: "edb_admin"
  username: "edb_admin"
  password: "mattdemo123!"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files:
    - "./build/plugins/ecommerce_plugin.so"
  
  # Automatically load all plugins found in search paths
  auto_load: true

workload: "ecommerce_mixed"
workers: 10
duration: "30s"
scale: 1000
connections: 20
summary_interval: "10s"  # Show progress every 10 seconds

# Optional settings for detailed configuration
workload_config:
  # E-commerce specific settings
  inventory_threshold: 100        # Minimum stock level before reordering
  order_batch_size: 50           # Orders processed per batch
  enable_recommendations: true    # Enable product recommendation features
  # Note: pgvector features may be limited on EPAS v16
  enable_vector_search: false    # Disable pgvector-based features for v16 compatibility
