# TPC-C Benchmark Workload Configuration - PGE v17
# Standard TPC-C benchmark for OLTP performance testing

database:
  type: postgres
  host: "p-kgd54g3gg7-rw-external-2e5e606c35f06e33.elb.us-east-1.amazonaws.com"
  port: 5432
  dbname: "edb_admin"
  username: "edb_admin"
  password: "mattdemo123!"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Automatically load all plugins found in search paths
  auto_load: true

workload: "tpcc"
workers: 10  # Higher for v17
duration: "5m"
scale: 15  # More warehouses for v17
connections: 25  # Higher for v17
summary_interval: "30s"

# TPC-C specific settings
tpcc:
  warehouses: 15  # More warehouses for v17
  ramp_time: "2m"
  
metrics:
  enabled: true
  interval: "10s"
  histogram_buckets: [1, 5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000]

# Advanced PGE v17 features
advanced:
  prepare_statements: true
  connection_pooling: true
  transaction_isolation: "read_committed"
  parallel_queries: true
  bulk_operations: true  # v17 enhancement
  query_optimization: "aggressive"
