# TPC-C Workload Configuration for EPAS v16
# TPC-C is a standard OLTP benchmark that simulates an order-entry environment
# with 5 transaction types: New-Order, Payment, Order-Status, Delivery, Stock-Level

database:
  type: postgres
  host: "p-rzjaqzb0yn-rw-external-31683a08ddd89515.elb.us-east-1.amazonaws.com"
  # host: "localhost"
  port: 5432
  dbname: "edb_admin"
  username: "edb_admin"
  password: "mattdemo123!"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
  
  # Specific plugin files to load (optional)
  files: []
  
  # Automatically load all plugins found in search paths
  auto_load: true

# TPC-C Load settings
workload: "tpcc"        # TPC-C benchmark workload
scale: 3                # Number of warehouses (conservative for v16)
                        # Each warehouse has: 
                        #     10 districts
                        #     ~3,000 customers per district
                        #     Orders, order lines, etc.
                        # scale: 3 -> 3 warehouses, 30 districts, ~90,000 customers

# Regular benchmark settings (ignored in progressive mode)
duration: "4h"        # Total test duration
workers: 10             # Conservative worker count for EPAS v16
connections: 20         # Max connections in pool (2x workers)
summary_interval: "5m" # Interval for periodic summaries during run

# Progressive scaling configuration - 4 hour test with 8 bands of 30 minutes each
progressive:
  enabled: true
  strategy: "linear"              # Linear scaling from 20 to 150 connections
  min_workers: 10                 # Start with 10 workers
  max_workers: 75                 # Scale up to 75 workers
  min_connections: 20             # Start with 20 connections
  max_connections: 150            # Scale up to 150 connections
  test_duration: "30m"            # Run each band for 30 minutes
  warmup_duration: "2m"           # Warmup time per band
  cooldown_duration: "1m"         # Cooldown time between bands
  bands: 8                        # Number of test configurations (4 hours total)
  enable_analysis: true           # Enable mathematical analysis

# TPC-C specific configuration
workload_config:
  # Transaction mix (TPC-C standard percentages)
  transaction_mix:
    new_order: 45       # 45% New-Order transactions (most intensive)
    payment: 43         # 43% Payment transactions
    order_status: 4     # 4% Order-Status transactions (read-only)
    delivery: 4         # 4% Delivery transactions (batch processing)
    stock_level: 4      # 4% Stock-Level transactions (analytical)
  
  # Performance tuning (conservative for v16)
  think_time: 0         # No think time for maximum throughput
  ramp_up_time: 15      # 15 second ramp-up period (longer for v16)
