# TPC-C Benchmark Workload Configuration - PGE v17
# Standard TPC-C benchmark for OLTP performance testing

database:
  type: postgres
  host: "p-kgd54g3gg7-rw-external-2e5e606c35f06e33.elb.us-east-1.amazonaws.com"
  port: 5432
  dbname: "edb_admin"
  username: "edb_admin"
  password: "mattdemo123!"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
  
  # Automatically load all plugins found in search paths
  auto_load: true

workload: "tpcc"
scale: 15  # More warehouses for v17

# Regular benchmark settings (ignored in progressive mode)
duration: "4h"
workers: 10  # Higher for v17
connections: 25  # Higher for v17
summary_interval: "5m"

# Progressive scaling configuration - 4 hour test with 8 bands of 30 minutes each
progressive:
  enabled: true
  strategy: "linear"              # Linear scaling from 20 to 150 connections
  min_workers: 10                 # Start with 10 workers
  max_workers: 75                 # Scale up to 75 workers
  min_connections: 20             # Start with 20 connections
  max_connections: 150            # Scale up to 150 connections
  test_duration: "30m"            # Run each band for 30 minutes
  warmup_duration: "2m"           # Warmup time per band
  cooldown_duration: "1m"         # Cooldown time between bands
  bands: 8                        # Number of test configurations (4 hours total)
  enable_analysis: true           # Enable mathematical analysis

# TPC-C specific settings
tpcc:
  warehouses: 15  # More warehouses for v17
  ramp_time: "2m"
  
metrics:
  enabled: true
  interval: "10s"
  histogram_buckets: [1, 5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000]

# Advanced PGE v17 features
advanced:
  prepare_statements: true
  connection_pooling: true
  transaction_isolation: "read_committed"
  parallel_queries: true
  bulk_operations: true  # v17 enhancement
  query_optimization: "aggressive"
