# Simple Bulk Insert Test Configuration
# Quick test for bulk insert workload development and testing

database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "storm"
  username: "storm_usr"
  password: "storm_pwd"
  sslmode: "disable"

# Enhanced Plugin Configuration
plugins:
  paths:
    - "./plugins"
    - "./build/plugins"
  files:
    - "./build/plugins/bulk_insert_plugin.so"
  auto_load: true
  
  # Enhanced Plugin Security Configuration
  security:
    enabled: true
    require_manifest: false        # Disabled by default for compatibility
    allow_untrusted: true          # Enabled by default for development
    manifest_path: "plugins/manifest.json"
    max_plugin_memory: "128MB"     # Higher limit for bulk operations
    trusted_authors:
      - "stormdb-team"
      - "your-organization"
    validation:
      verify_checksums: false      # Disabled by default for development
      max_file_size: "50MB"
      
  # Memory Management Configuration  
  memory:
    enabled: true
    max_total_memory: "1GB"        # Higher limit for bulk operations
    max_plugin_memory: "128MB"
    check_interval: "30s"
    enable_gc_tuning: true
    retention:
      enabled: true
      default_ttl: "30m"
      max_collection_size: 8000
      memory_warn_threshold: 0.8
      memory_alert_threshold: 0.95
      
  # Context Management Configuration
  context:
    plugin_load_timeout: "45s"     # Longer timeout for bulk insert plugin
    health_check_interval: "5m"
    health_check_timeout: "15s"
    max_concurrent_loads: 3
    max_retry_attempts: 3
    retry_backoff: "2s"

# Test metadata
test_metadata:
  test_name: "bulk_insert_simple_test"
  environment: "development"
  tags: ["bulk_insert", "test", "development"]

# Bulk Insert workload configuration
workload: "bulk_insert"
scale: 100
duration: "30s"                 # Short duration for testing
workers: 2                     # Minimal workers for testing
connections: 4                 # Small connection pool

# Simple progressive test - enabled for testing band logging
progressive:
  enabled: true
  strategy: "linear"
  min_workers: 1
  max_workers: 2
  min_connections: 2
  max_connections: 4
  test_duration: "5s"           # Very short tests
  warmup_duration: "2s"
  cooldown_duration: "2s"
  bands: 3
  enable_analysis: true

# Simple batch size progression for testing
workload_config:
  ring_buffer_size: 1000        # Small buffer for testing
  producer_threads: 1           # Single producer for simplicity
  batch_sizes: [100, 1000]  # Test larger batch sizes for quick testing
  test_insert_method: true      # Test both INSERT and COPY
  data_seed: 42                 # Fixed seed for reproducible tests
  max_memory_mb: 64
  collect_metrics: true

# PostgreSQL monitoring
collect_pg_stats: true
pg_stats_statements: false      # Disabled for simple test
