database:
  type: postgres
  host: localhost
  port: 5432
  dbname: storm
  username: storm_user
  password: storm_pwd!123
  sslmode: disable

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files: []
  
  # Automatically load all plugins found in search paths
  auto_load: true

workload: connection
duration: 30s
workers: 10
connections: 20
summary_interval: 5s

# PostgreSQL monitoring options
collect_pg_stats: true
pg_stats_statements: false

# Connection management for overhead testing
connection_mode: mixed  # Use both persistent and transient connections (50/50)
