# Comprehensive pgvector Read Test - Full Table Scan
# Tests similarity search performance without indexes
database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "stormdb_vector_test"
  username: "postgres"
  password: "postgres"
  sslmode: "disable"

plugins:
  paths:
    - "./plugins"
    - "./build/plugins"
  files:
    - "./build/plugins/vector_plugin.so"
  auto_load: true

workload: "pgvector_comprehensive_read_scan"
scale: 1000000
duration: "60s"
workers: 4
connections: 8

test_config:
  dimensions: 1024
  similarity_metric: "cosine"
  batch_size: 500
  baseline_rows: 1000000
  precomputed_percentage: 10
  read_type: "full_scan"      # Forces sequential scan
