# config.yaml
database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "test"
  username: "storm_user"
  password: "storm_pwd!123"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files: []
  
  # Automatically load all plugins found in search paths
  auto_load: true

# Load settings
workload: "vector_1024"        # simple, tpcc, or custom
scale: 10000                # This works differently for each workload.
                        # For tpcc, it defines the number of warehouses. 
                        # Each warehouse has: 
                        #     10 districts
                        #     ~3,000 customers per district
                        #     Orders, order lines, etc.
                        # Meaning of scale: 
                        #     scale: 1  -> 1 warehouse, 10 districts, ~30,000 customers
                        #     scale: 10 -> 10 warehouses, 100 districts, ~300,000 customers
                        # For simple, it defines the number of transactions to run.
duration: "30s"         # e.g., 30s, 1m, 5m
workers: 8              # number of concurrent worker threads
connections: 16         # max connections in pool
summary_interval: "10s" # periodic summary interval (optional)