# Comprehensive pgvector Read Test - Indexed Reads
# Tests similarity search performance with indexes
database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "stormdb_vector_test"
  username: "postgres"
  password: "postgres"
  sslmode: "disable"

plugins:
  paths:
    - "./plugins"
    - "./build/plugins"
  files:
    - "./build/plugins/vector_plugin.so"
  auto_load: true

workload: "pgvector_comprehensive_read_indexed"
scale: 1000000
duration: "60s"                  # Base duration (overridden by progressive)
workers: 4                       # Base workers (overridden by progressive)
connections: 8                   # Base connections (overridden by progressive)

# Progressive scaling configuration - 3 hour test with 6 bands of 30 minutes each
progressive:
  enabled: true
  min_workers: 10
  step_workers: 10
  max_workers: 60
  min_connections: 20
  step_connections: 20
  max_connections: 120
  band_duration: "1800s"         # 30 minutes per band (3 hours total รท 6 bands)
  warmup_time: "60s"         # 1 minute warmup
  cooldown_time: "30s"       # 30 second cooldown
  strategy: "linear"
  
  export_format: "csv"
  export_path: "./progressive_results"
test_config:
  dimensions: 1024
  similarity_metric: "cosine"
  batch_size: 500
  baseline_rows: 1000000
  precomputed_percentage: 10
  read_type: "indexed"        # Uses vector indexes
  index_type: "ivfflat"       # ivfflat, hnsw
