# Complete Feature Showcase Configuration
# Demonstrates all new PostgreSQL monitoring, connection management, and plugin system features

database:
  type: postgres
  host: localhost
  port: 5432
  dbname: storm
  username: storm_user
  password: storm_pwd!123
  sslmode: disable

# Plugin system configuration - NEW FEATURE
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files: []
  
  # Automatically load all plugins found in search paths
  auto_load: true

# Workload configuration
workload: connection_overhead       # Special workload for connection analysis
scale: 1000                        # Number of test operations to prepare
duration: 45s                      # Test duration
workers: 8                         # Number of concurrent workers
connections: 16                    # Max connections in pool (for persistent mode)
summary_interval: 10s              # Progress reporting interval

# PostgreSQL Deep Monitoring Options
collect_pg_stats: true             # Enable comprehensive PostgreSQL statistics
pg_stats_statements: true          # Enable pg_stat_statements query analysis (requires extension)

# Connection Management Strategy
connection_mode: mixed             # Options: "persistent", "transient", "mixed"
                                  # - persistent: Use connection pooling (default, fastest)
                                  # - transient: Create new connection per operation (shows overhead)  
                                  # - mixed: 50% persistent, 50% transient (comparison mode)

# Advanced Configuration Notes:
# 
# PostgreSQL Statistics Collected:
#   • Buffer cache hit ratios and block I/O metrics
#   • WAL (Write-Ahead Log) records and bytes written
#   • Checkpoint frequency and behavior
#   • Connection utilization vs limits
#   • Lock contention and deadlock tracking
#   • Autovacuum activity monitoring
#   • Top queries by execution time (with pg_stat_statements)
#
# Connection Mode Analysis:
#   • Persistent: Standard connection pooling, optimal performance
#   • Transient: New connection per operation, shows establishment overhead
#   • Mixed: Runs 50% operations each way for direct comparison
#
# Key Metrics Provided:
#   • Transaction rate differences between connection modes
#   • Average latency overhead of connection establishment  
#   • Connection setup time tracking (typically 1-3ms per connection)
#   • Total connections created during test run
#   • Performance impact analysis and recommendations
