# IMDB Read-Only Workload Configuration
# Intensive read testing with complex queries

database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "imdb"
  username: "storm_user"
  password: "storm_pwd!123"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files: []
  
  # Automatically load all plugins found in search paths
  auto_load: true

workload: "imdb_read"           # Read-only intensive operations
scale: 1000                     # Number of movies to seed
duration: "20s"                 # Test duration
workers: 4                      # Multiple workers for high read load
connections: 8                  # More connections for read scaling
