# IMDB Workload Configuration - Dump File Loading Mode
# Load data from a PostgreSQL dump file

database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "imdb"
  username: "storm_user"
  password: "storm_pwd!123"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files: []
  
  # Automatically load all plugins found in search paths
  auto_load: true

# Load data from PostgreSQL dump file
data_loading:
  mode: "dump"                  # Load from pg_dump file
  filepath: "/path/to/imdb.dump" # Path to your PostgreSQL dump file

workload: "imdb_read"           # Read-intensive operations
scale: 1000                     # Not used when loading from dump
duration: "20s"                 # Duration of the test
workers: 4                      # Number of concurrent workers
connections: 8                  # Database connections
