# Comprehensive pgvector Ingestion Test - COPY Protocol
# Tests COPY protocol performance for bulk loading
database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "stormdb_vector_test"
  username: "postgres"
  password: "postgres"
  sslmode: "disable"

plugins:
  paths:
    - "./plugins"
    - "./build/plugins"
  files:
    - "./build/plugins/vector_plugin.so"
  auto_load: true

workload: "pgvector_comprehensive_ingestion_copy"
scale: 1000000
duration: "60s"
workers: 2              # Fewer workers for COPY (less parallelizable)
connections: 4

test_config:
  dimensions: 1024
  similarity_metric: "cosine"
  batch_size: 1000            # Larger batches for COPY
  baseline_rows: 1000000
  precomputed_percentage: 10
