# Vector Cosine Similarity Workload Configuration
# Enhanced connection settings for pgvector cosine similarity testing
# NOTE: Vector workloads are now provided by the vector_plugin

database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "test"
  username: "storm_user"
  password: "storm_pwd!123"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files:
    - "./build/plugins/vector_plugin.so"
  
  # Automatically load all plugins found in search paths
  auto_load: true

workload: "vector_1024_cosine"  # Cosine similarity search
scale: 500                      # Reduced from 1000 to avoid timeout during setup
duration: "30s"
workers: 2                      # Reduced from 4 to avoid connection pressure
connections: 4                  # Reduced from 8 to match worker ratio
