# Test Configuration - Synchronized Workers and Connections
database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "test"
  username: "storm_user"
  password: "storm_pwd!123"
  sslmode: "disable"

workload: "simple"
scale: 100
duration: "5s"
workers: 2
connections: 4
summary_interval: "2s"

# Synchronized progressive test - workers = connections
progressive:
  enabled: true
  min_workers: 2
  step_workers: 2
  max_workers: 8
  min_connections: 2
  step_connections: 2
  max_connections: 8
  band_duration: "8s"           # 8 seconds per band
  warmup_time: "2s"             # 2 second warmup
  cooldown_time: "1s"           # 1 second cooldown
  strategy: "synchronized"      # New strategy: workers = connections
  export_format: "both"
  export_path: "./progressive_results"

# Disable plugins to avoid version conflicts
plugins:
  auto_load: false
  paths: []
  files: []
