# IMDB Workload Configuration - SQL File Loading Mode
# Load data from an SQL script file

database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "imdb"
  username: "storm_user"
  password: "storm_pwd!123"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files: []
  
  # Automatically load all plugins found in search paths
  auto_load: true

# Load data from SQL script file
data_loading:
  mode: "sql"                   # Load from SQL file
  filepath: "/path/to/imdb.sql" # Path to your SQL script file

workload: "imdb_write"          # Write-intensive operations
scale: 1000                     # Not used when loading from SQL
duration: "20s"                 # Duration of the test
workers: 2                      # Number of concurrent workers
connections: 4                  # Database connections
