database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "storm"
  username: "storm_user"
  password: "storm_pwd!123"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files: []
  
  # Automatically load all plugins found in search paths
  auto_load: true

workload: "ecommerce_write"
workers: 5
duration: "30s"
scale: 1000
connections: 10

# E-Commerce Write-Heavy Workload Configuration
# This workload focuses on write operations in e-commerce:
# - New order processing and order item creation
# - Inventory updates and stock level changes
# - Product review submissions with vector embeddings
# - User profile updates
# - Vendor purchase order creation and processing
# - Automated stock reordering triggers
# - Price updates based on cost changes

metrics:
  enabled: true
  interval: "5s"
  histogram_buckets: [1, 5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000]
