# Transient Connection Mode Configuration
# Tests pure transient connections (create new connection per operation)

database:
  type: postgres
  host: localhost
  port: 5432
  dbname: storm
  username: storm_user
  password: storm_pwd!123
  sslmode: disable

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files: []
  
  # Automatically load all plugins found in search paths
  auto_load: true

workload: simple
mode: mixed
scale: 500                       # Smaller scale for transient mode testing
duration: 30s
workers: 4                       # Fewer workers to avoid overwhelming connection creation
connections: 8                   # Still used for setup/teardown operations
summary_interval: 5s

# PostgreSQL monitoring
collect_pg_stats: true
pg_stats_statements: false

# Connection management - TRANSIENT MODE
connection_mode: transient       # Create new connection for each operation
