# Fixed TPC-C Progressive Configuration - Synchronized Workers & Connections
database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "test"
  username: "storm_user"
  password: "storm_pwd!123"
  sslmode: "disable"

# Plugin system configuration
plugins:
  paths:
    - "./plugins"
    - "./build/plugins"
  files: []
  auto_load: true

workload: "tpcc"
scale: 10
duration: "30s"
workers: 8
connections: 16
summary_interval: "5s"

# Fixed Progressive scaling configuration with synchronized workers/connections
progressive:
  enabled: true
  min_workers: 20
  step_workers: 20
  max_workers: 100
  min_connections: 20           # Now matches workers
  step_connections: 20          # Now matches workers  
  max_connections: 100          # Now matches workers
  band_duration: "180s"         # 3 minutes per band for meaningful TPC-C results
  warmup_time: "60s"            # 1 minute warmup
  cooldown_time: "30s"          # 30 second cooldown
  strategy: "synchronized"      # NEW: workers = connections always
  export_format: "csv"
  export_path: "./progressive_results"

# PostgreSQL monitoring options
collect_pg_stats: true
pg_stats_statements: false

# Connection management options  
connection_mode: "persistent"
