database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "storm"
  username: "storm_user"
  password: "storm_pwd!123"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files: []
  
  # Automatically load all plugins found in search paths
  auto_load: true

workload: "ecommerce_write"
workers: 5                       # Base workers (overridden by progressive)
duration: "30s"                  # Base duration (overridden by progressive)
scale: 1000
connections: 10                  # Base connections (overridden by progressive)

# Progressive scaling configuration - 3 hour test with 6 bands of 30 minutes each
progressive:
  enabled: true
  min_workers: 10
  step_workers: 10
  max_workers: 60
  min_connections: 20
  step_connections: 20
  max_connections: 120
  band_duration: "1800s"         # 30 minutes per band (3 hours total รท 6 bands)
  warmup_time: "60s"         # 1 minute warmup
  cooldown_time: "30s"       # 30 second cooldown
  strategy: "linear"
  
  export_format: "csv"
  export_path: "./progressive_results"
metrics:
  enabled: true
  interval: "5s"
  histogram_buckets: [1, 5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000]
