# IMDB Workload Configuration Template
# Internet Movie Database (IMDB) workload simulations with complex queries,
# large dataset operations, and mixed read/write scenarios
# This file contains multiple configuration examples for different IMDB scenarios

# =============================================================================
# DATABASE CONNECTION CONFIGURATION
# =============================================================================
database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "storm"
  username: "storm_usr"
  password: "storm_pwd"
  sslmode: "disable"

# =============================================================================
# RESULTS BACKEND CONFIGURATION (Optional - for analytics)
# =============================================================================
# Uncomment and configure to store test results in a separate database
# results_backend:
#   enabled: true
#   host: "localhost"
#   port: 5432
#   database: "stormdb_results"
#   username: "storm_usr"
#   password: "storm_pwd"
#   sslmode: "disable"
#   retention_days: 90
#   store_raw_metrics: true
#   store_pg_stats: true
#   metrics_batch_size: 2000
#   table_prefix: "stormdb_"

# =============================================================================
# TEST METADATA (Optional - for result tracking)
# =============================================================================
# test_metadata:
#   test_name: "imdb_mixed_workload"
#   environment: "local_dev"
#   database_target: "PostgreSQL 16"
#   tags: ["imdb", "mixed", "analytics", "olap"]
#   notes: "IMDB dataset workload simulation"

# =============================================================================
# PLUGIN CONFIGURATION
# =============================================================================
plugins:
  paths:
    - "./plugins"
    - "./build/plugins"
  files:
    - "./build/plugins/imdb_plugin.so"
  auto_load: true
  
  # Enhanced Plugin Security Configuration
  security:
    enabled: true
    require_manifest: false        # Disabled by default for compatibility
    allow_untrusted: true          # Enabled by default for development
    manifest_path: "plugins/manifest.json"
    max_plugin_memory: "150MB"     # Higher limit for IMDB data processing
    trusted_authors:
      - "stormdb-team"
      - "your-organization"
    validation:
      verify_checksums: false      # Disabled by default for development
      max_file_size: "50MB"
      
  # Memory Management Configuration  
  memory:
    enabled: true
    max_total_memory: "2GB"        # Higher limit for IMDB dataset
    max_plugin_memory: "150MB"
    check_interval: "30s"
    enable_gc_tuning: true
    retention:
      enabled: true
      default_ttl: "2h"           # Longer retention for analytical workloads
      max_collection_size: 20000   # Larger collection for IMDB data
      memory_warn_threshold: 0.8
      memory_alert_threshold: 0.95
      
  # Context Management Configuration
  context:
    plugin_load_timeout: "45s"     # Longer timeout for large IMDB plugin
    health_check_interval: "5m"
    health_check_timeout: "15s"
    max_concurrent_loads: 3
    max_retry_attempts: 3
    retry_backoff: "2s"

# =============================================================================
# EXAMPLE 1: IMDB MIXED WORKLOAD (Default - Active Configuration)
# =============================================================================
# Balanced read/write operations for realistic IMDB simulation
workload: "imdb_mixed"
scale: 100                  # Dataset scale factor
duration: "15m"             # Test duration
workers: 6                  # Number of concurrent workers
connections: 12             # Connection pool size
summary_interval: "2m"      # Progress update interval

# =============================================================================
# EXAMPLE 2: IMDB READ-INTENSIVE WORKLOAD (Commented)
# =============================================================================
# Uncomment for read-heavy scenarios (movie searches, analytics queries)
# workload: "imdb_read"
# scale: 200                  # Larger dataset for read scenarios
# duration: "20m"
# workers: 8
# connections: 16
# summary_interval: "3m"

# =============================================================================
# EXAMPLE 3: IMDB WRITE-INTENSIVE WORKLOAD (Commented)
# =============================================================================
# Uncomment for write-heavy scenarios (data ingestion, updates)
# workload: "imdb_write"
# scale: 50                   # Smaller scale for write-intensive operations
# duration: "25m"
# workers: 4
# connections: 8
# summary_interval: "3m"

# =============================================================================
# EXAMPLE 4: IMDB DATA DUMP/LOAD WORKLOAD (Commented)
# =============================================================================
# Uncomment for bulk data loading scenarios
# workload: "imdb_read"       # Read-intensive operations for bulk processing
# scale: 300                  # Large scale for bulk operations
# duration: "45m"
# workers: 2                  # Few workers for bulk operations
# connections: 4
# summary_interval: "5m"

# =============================================================================
# EXAMPLE 5: PROGRESSIVE SCALING IMDB (Commented)
# =============================================================================
# Uncomment for progressive scaling tests
# workload: "imdb_mixed"
# scale: 150
# duration: "4h"
# workers: 6
# connections: 12
# summary_interval: "5m"
# 
# progressive:
#   enabled: true
#   strategy: "linear"
#   min_workers: 6
#   max_workers: 60
#   min_connections: 12
#   max_connections: 120
#   test_duration: "30m"
#   warmup_duration: "2m"
#   cooldown_duration: "1m"
#   bands: 8
#   enable_analysis: true
#   
#   # Memory management for progressive scaling
#   max_latency_samples: 50000
#   memory_limit_mb: 512

# =============================================================================
# PostgreSQL MONITORING (Optional)
# =============================================================================
# Uncomment to collect PostgreSQL statistics
# collect_pg_stats: true
# pg_stats_statements: true

# =============================================================================
# IMDB WORKLOAD SPECIFIC CONFIGURATION
# =============================================================================
workload_config:
  mode: "mixed"             # Options: read, write, mixed, analytics
  
  # Data scaling parameters
  data_scale:
    movies: 50000           # Number of movies in dataset
    actors: 100000          # Number of actors
    directors: 10000        # Number of directors
    ratings: 500000         # Number of ratings
    reviews: 200000         # Number of reviews
    genres: 25              # Number of genres
    keywords: 5000          # Number of keywords

  # Query complexity distribution
  query_mix:
    simple_lookup: 30       # Simple movie/actor lookups
    filtered_search: 25     # Movies by genre, year, rating
    complex_join: 20        # Multi-table joins with aggregations
    analytical: 15          # Complex analytical queries
    full_text_search: 5     # Full-text search in reviews/descriptions
    recommendation: 5       # Movie recommendation queries

  # Performance settings
  cache_hit_ratio: 0.75     # Lower cache hit ratio for large datasets
  think_time: 0             # No think time for maximum throughput
  ramp_up_time: 20          # Longer ramp-up for complex queries

# =============================================================================
# METRICS CONFIGURATION
# =============================================================================
metrics:
  enabled: true
  interval: "5s"
  latency_percentiles: [50, 90, 95, 99]
