# E-Commerce Workload Configuration Template
# Real-world e-commerce database usage patterns with complex queries,
# mixed OLTP/OLAP workloads, and comprehensive indexing scenarios
# This file contains multiple configuration examples for different e-commerce scenarios

# =============================================================================
# DATABASE CONNECTION CONFIGURATION
# =============================================================================
database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "postgres"
  username: "postgres"
  password: "postgres"
  sslmode: "disable"

# =============================================================================
# RESULTS BACKEND CONFIGURATION (Optional - for analytics)
# =============================================================================
# Uncomment and configure to store test results in a separate database
# results_backend:
#   enabled: true
#   host: "localhost"
#   port: 5432
#   database: "stormdb_results"
#   username: "postgres"
#   password: "postgres"
#   sslmode: "disable"
#   retention_days: 90
#   store_raw_metrics: true
#   store_pg_stats: true
#   metrics_batch_size: 2000
#   table_prefix: "stormdb_"

# =============================================================================
# TEST METADATA (Optional - for result tracking)
# =============================================================================
# test_metadata:
#   test_name: "ecommerce_mixed_workload"
#   environment: "local_dev"
#   database_target: "PostgreSQL 16"
#   tags: ["ecommerce", "mixed", "oltp", "olap"]
#   notes: "E-commerce mixed workload simulation"

# =============================================================================
# PLUGIN CONFIGURATION
# =============================================================================
plugins:
  paths:
    - "./plugins"
    - "./build/plugins"
  files:
    - "./build/plugins/ecommerce_plugin.so"
  auto_load: true

# =============================================================================
# EXAMPLE 1: E-COMMERCE MIXED WORKLOAD (Default - Active Configuration)
# =============================================================================
# Balanced read/write operations for realistic e-commerce simulation
workload: "ecommerce_mixed"
scale: 1000                 # Number of users to simulate
duration: "10m"             # Test duration
workers: 8                  # Number of concurrent workers
connections: 16             # Connection pool size
summary_interval: "1m"      # Progress update interval

# =============================================================================
# EXAMPLE 2: E-COMMERCE READ-HEAVY WORKLOAD (Commented)
# =============================================================================
# Uncomment for read-intensive e-commerce scenarios (product browsing, searches)
# workload: "ecommerce_read"
# scale: 2000                 # More users for read scenarios
# duration: "15m"
# workers: 12
# connections: 24
# summary_interval: "2m"

# =============================================================================
# EXAMPLE 3: E-COMMERCE WRITE-HEAVY WORKLOAD (Commented)
# =============================================================================
# Uncomment for write-intensive scenarios (order processing, inventory updates)
# workload: "ecommerce_write"
# scale: 500                  # Fewer users but more intensive operations
# duration: "20m"
# workers: 6
# connections: 12
# summary_interval: "2m"

# =============================================================================
# EXAMPLE 4: E-COMMERCE ANALYTICS WORKLOAD (Commented)
# =============================================================================
# Uncomment for analytical/reporting scenarios
# workload: "ecommerce_analytics"
# scale: 5000                 # Large dataset for analytics
# duration: "30m"
# workers: 4                  # Fewer workers for complex queries
# connections: 8
# summary_interval: "5m"

# =============================================================================
# EXAMPLE 5: E-COMMERCE BASIC WORKLOAD (Commented)
# =============================================================================
# Uncomment for simple e-commerce operations
# workload: "ecommerce_basic"
# scale: 800
# duration: "15m"
# workers: 6
# connections: 12
# summary_interval: "2m"

# =============================================================================
# EXAMPLE 6: PROGRESSIVE SCALING E-COMMERCE (Commented)
# =============================================================================
# Uncomment for progressive scaling tests
# workload: "ecommerce_mixed"
# scale: 2000
# duration: "4h"
# workers: 8
# connections: 16
# summary_interval: "5m"
# 
# progressive:
#   enabled: true
#   strategy: "linear"
#   min_workers: 8
#   max_workers: 80
#   min_connections: 16
#   max_connections: 160
#   test_duration: "30m"
#   warmup_duration: "2m"
#   cooldown_duration: "1m"
#   bands: 8
#   enable_analysis: true
#   
#   # Memory management for progressive scaling
#   max_latency_samples: 50000
#   memory_limit_mb: 512

# =============================================================================
# PostgreSQL MONITORING (Optional)
# =============================================================================
# Uncomment to collect PostgreSQL statistics
# collect_pg_stats: true
# pg_stats_statements: true

# =============================================================================
# E-COMMERCE WORKLOAD SPECIFIC CONFIGURATION
# =============================================================================
workload_config:
  mode: "mixed"             # Options: read, write, mixed, oltp, analytics
  
  # Data scaling parameters
  data_scale:
    users: 10000            # Number of users to generate
    products: 5000          # Number of products to generate
    orders: 50000           # Number of orders to generate
    reviews: 25000          # Number of reviews to generate
    sessions: 100000        # Number of user sessions to generate
    analytics_events: 500000 # Number of analytics events to generate

  # Workload distribution (percentages should sum to 100)
  workload_mix:
    product_search: 25      # Product search and browsing
    user_session: 20        # User login/logout and session management
    order_processing: 15    # Order creation and processing
    inventory_update: 10    # Inventory and stock management
    review_analysis: 10     # Review creation and similarity search
    analytics_query: 10     # Business analytics and reporting
    vendor_management: 5    # Vendor and purchase order management
    recommendation: 5       # Product recommendation engine

  # Performance settings
  cache_hit_ratio: 0.85     # Simulate cache effectiveness
  think_time: 0             # No think time for maximum throughput
  ramp_up_time: 15          # Ramp-up period in seconds

# =============================================================================
# METRICS CONFIGURATION
# =============================================================================
metrics:
  enabled: true
  interval: "5s"
  latency_percentiles: [50, 90, 95, 99]
