# Progressive Transient Connection Mode Configuration
# Tests transient connections with progressive scaling
# Creates new connection per operation with scaling analysis

database:
  type: postgres
  host: localhost
  port: 5432
  dbname: storm
  username: storm_user
  password: storm_pwd!123
  sslmode: disable

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files: []
  
  # Automatically load all plugins found in search paths
  auto_load: true

workload: simple
mode: mixed
scale: 500                       # Smaller scale for transient mode testing
duration: 30s
workers: 4                       # Base workers (overridden by progressive)
connections: 8                   # Base connections (overridden by progressive)
summary_interval: 5s

# Progressive scaling configuration - 3 hour test with 6 bands of 30 minutes each
progressive:
  enabled: true
  min_workers: 10
  step_workers: 10
  max_workers: 60
  min_connections: 20
  step_connections: 20
  max_connections: 120
  band_duration: "1800s"         # 30 minutes per band (3 hours total รท 6 bands)
  warmup_time: "90s"         # Extra warmup for transient connection establishment
  cooldown_time: "60s"       # Extra cooldown for transient connection cleanup
  strategy: "linear"     # Linear scaling for predictable transient behavior
  
  export_format: "csv"
  export_path: "./progressive_results"
collect_pg_stats: true
pg_stats_statements: false

# Connection management - TRANSIENT MODE
connection_mode: transient       # Create new connection for each operation
