# Progress Tracking Demo Configuration
# IMDB workload with progress bars during data seeding

database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "test"
  username: "storm_user"
  password: "storm_pwd!123"
  sslmode: "disable"

# Plugin system configuration
plugins:
  paths:
    - "./plugins"
    - "./build/plugins"
  auto_load: true

# IMDB workload with moderate scale for demo
workload: "imdb_mixed"
scale: 1000                 # 1000 movies (shows progress bars for actors, movies, comments, etc.)
duration: "10s"             # Short duration
workers: 2                  # Minimal workers
connections: 4              # Minimal connections
summary_interval: "2s"      # Frequent summaries

# IMDB specific configuration
workload_config:
  enable_analytics: true
  enable_search: true
  enable_aggregations: true
  complex_query_ratio: 0.3
