database:
  type: "postgres"
  host: "localhost"
  port: 5432
  dbname: "testdb"
  username: "postgres"
  password: "password"
  sslmode: "disable"

# Results backend configuration for comprehensive analytics
results_backend:
  enabled: true
  host: "localhost"
  port: 5432
  database: "stormdb_results"
  username: "postgres"
  password: "password"
  sslmode: "disable"
  retention_days: 30
  store_raw_metrics: true
  store_pg_stats: true
  metrics_batch_size: 1000
  table_prefix: "stormdb_"

# Test metadata for tracking and organization
test_metadata:
  test_name: "integration_test_with_backend"
  environment: "development"
  database_target: "PostgreSQL 16 Local"
  tags: ["integration", "development", "backend"]
  notes: "Testing new database backend feature integration"

# TPC-C workload configuration
workload: "tpcc"
scale: 1
workers: 5
connections: 10
duration: "30s"
summary_interval: "10s"
collect_pg_stats: true
pg_stats_statements: false
