# Complete Feature Showcase Configuration
# Demonstrates all new PostgreSQL monitoring, connection management, and plugin system features

database:
  type: postgres
  host: localhost
  port: 5432
  dbname: storm
  username: storm_user
  password: storm_pwd!123
  sslmode: disable

# Plugin system configuration - NEW FEATURE
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files: []
  
  # Automatically load all plugins found in search paths
  auto_load: true

# Workload configuration
workload: connection_overhead       # Special workload for connection analysis
scale: 1000                        # Number of test operations to prepare
duration: 45s                      # Base duration (overridden by progressive)
workers: 8                         # Base workers (overridden by progressive)
connections: 16                    # Base connections (overridden by progressive)
summary_interval: 10s              # Progress reporting interval

# Progressive scaling configuration - 3 hour test with 6 bands of 30 minutes each
progressive:
  enabled: true
  min_workers: 10
  step_workers: 10
  max_workers: 60
  min_connections: 20
  step_connections: 20
  max_connections: 120
  band_duration: "1800s"         # 30 minutes per band (3 hours total ÷ 6 bands)
  warmup_time: "60s"         # 1 minute warmup
  cooldown_time: "30s"       # 30 second cooldown
  strategy: "linear"
  
  export_format: "csv"
  export_path: "./progressive_results"
collect_pg_stats: true             # Enable comprehensive PostgreSQL statistics
pg_stats_statements: true          # Enable pg_stat_statements query analysis (requires extension)

# Connection Management Strategy
connection_mode: mixed             # Options: "persistent", "transient", "mixed"
                                  # - persistent: Use connection pooling (default, fastest)
                                  # - transient: Create new connection per operation (shows overhead)  
                                  # - mixed: 50% persistent, 50% transient (comparison mode)

# Advanced Configuration Notes:
# 
# PostgreSQL Statistics Collected:
#   • Buffer cache hit ratios and block I/O metrics
#   • WAL (Write-Ahead Log) records and bytes written
#   • Checkpoint frequency and behavior
#   • Connection utilization vs limits
#   • Lock contention and deadlock tracking
#   • Autovacuum activity monitoring
#   • Top queries by execution time (with pg_stat_statements)
#
# Connection Mode Analysis:
#   • Persistent: Standard connection pooling, optimal performance
#   • Transient: New connection per operation, shows establishment overhead
#   • Mixed: Runs 50% operations each way for direct comparison
#
# Key Metrics Provided:
#   • Transaction rate differences between connection modes
#   • Average latency overhead of connection establishment  
#   • Connection setup time tracking (typically 1-3ms per connection)
#   • Total connections created during test run
#   • Performance impact analysis and recommendations
