# Minimal Progressive Test Configuration - Very short test for debugging
database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "test"
  username: "storm_user"
  password: "storm_pwd!123"
  sslmode: "disable"

workload: "simple"
scale: 100
duration: "5s"
workers: 2
connections: 4
summary_interval: "2s"

# Very short progressive test (3 bands x 10 seconds = 30 seconds)
progressive:
  enabled: true
  min_workers: 2
  step_workers: 1
  max_workers: 4
  min_connections: 4
  step_connections: 2
  max_connections: 8
  band_duration: "10s"           # 10 seconds per band
  warmup_time: "2s"              # 2 second warmup
  cooldown_time: "1s"            # 1 second cooldown
  strategy: "linear"
  export_format: "both"
  export_path: "./progressive_results"

# Disable plugins to avoid version conflicts
plugins:
  auto_load: false
  paths: []
  files: []
