# Progressive scaling configuration for E-commerce workload
# This configuration demonstrates fibonacci scaling pattern
# for gradual performance exploration

workload: "ecommerce"
mode: "mixed"
scale: 50      # Scale factor for product/user generation

# Regular benchmark settings (ignored in progressive mode)
duration: "3m"
workers: 30
connections: 40
summary_interval: "10s"

# Database configuration
database:
  type: "postgres"
  host: "localhost"
  port: 5432
  dbname: "stormdb_ecommerce"
  username: "postgres" 
  password: "password"
  sslmode: "disable"

# Progressive scaling configuration
progressive:
  enabled: true
  
  # Fibonacci scaling for organic growth pattern
  min_workers: 10      # Start with 10 workers
  max_workers: 60      # Scale up to 60 workers
  step_workers: 10     # Increment by 10 workers per band
  
  min_connections: 20  # Start with 20 connections
  max_connections: 120 # Scale up to 120 connections
  step_connections: 20 # Increment by 20 connections per band
  
  # 3 hour test with 6 bands of 30 minutes each
  band_duration: "1800s" # Run each band for 30 minutes (3 hours total รท 6 bands)
  warmup_time: "60s"   # 1 minute warmup
  cooldown_time: "30s" # 30 second cooldown
  
  # Linear scaling for consistent analysis
  strategy: "linear"
  
  # Export for detailed mathematical analysis
  export_format: "json"
  export_path: "./progressive_results/ecommerce"

# PostgreSQL monitoring
collect_pg_stats: true
pg_stats_statements: false  # Disabled for cleaner fibonacci analysis
