# IMDB Write-Only Workload Configuration  
# Intensive write testing with inserts and updates

database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "imdb"
  username: "storm_user"
  password: "storm_pwd!123"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files: []
  
  # Automatically load all plugins found in search paths
  auto_load: true

workload: "imdb_write"          # Write-only intensive operations
scale: 500                      # Smaller initial dataset for faster setup
duration: "20s"                 # Base duration (overridden by progressive)
workers: 2                      # Base workers (overridden by progressive)
connections: 4                  # Base connections (overridden by progressive)

# Progressive scaling configuration - 3 hour test with 6 bands of 30 minutes each
progressive:
  enabled: true
  min_workers: 10
  step_workers: 10
  max_workers: 60
  min_connections: 20
  step_connections: 20
  max_connections: 120
  band_duration: "1800s"         # 30 minutes per band (3 hours total รท 6 bands)
  warmup_time: "60s"         # 1 minute warmup
  cooldown_time: "30s"       # 30 second cooldown
  strategy: "linear"
  
  export_format: "csv"
  export_path: "./progressive_results"
