# High Performance Data Loading Test Configuration
# This configuration tests the optimized bulk loading performance

database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "test"
  username: "storm_user"
  password: "storm_pwd!123"
  sslmode: "disable"

# Plugin system configuration
plugins:
  paths:
    - "./plugins"
    - "./build/plugins"
  auto_load: true

# TPC-C workload with larger scale to test performance
workload: "tpcc"
scale: 10                   # 10 warehouses = 100 districts = 3M customers 
duration: "30s"             # Short duration for testing
workers: 4                  # More workers
connections: 8              # More connections
summary_interval: "5s"      # Less frequent summaries

# TPC-C specific configuration
workload_config:
  transaction_mix:
    new_order: 45
    payment: 43
    order_status: 4
    delivery: 4
    stock_level: 4
  
  think_time: 0
  ramp_up_time: 5

# Performance optimization settings
performance:
  bulk_loading: true
  use_copy_protocol: true
  batch_size: 10000
