# Progressive TPC-C Configuration
# Tests TPC-C workload with progressive connection scaling
# Automatically scales from 4 to 32 workers with linear increments

database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "test"
  username: "storm_user"
  password: "storm_pwd!123"
  sslmode: "disable"

# Plugin system configuration
plugins:
  # Directories to search for plugin files (.so, .dll, .dylib)
  paths:
    - "./plugins"
    - "./build/plugins"
    - "/usr/local/lib/stormdb/plugins"
  
  # Specific plugin files to load (optional)
  files: []
  
  # Automatically load all plugins found in search paths
  auto_load: true

# Load settings
workload: "tpcc"        # simple, tpcc, or custom
scale: 2                # This works differently for each workload.
                        # For tpcc, it defines the number of warehouses. 
                        # Each warehouse has: 
                        #     10 districts
                        #     ~3,000 customers per district
                        #     Orders, order lines, etc.
                        # Meaning of scale: 
                        #     scale: 1  -> 1 warehouse, 10 districts, ~30,000 customers
                        #     scale: 10 -> 10 warehouses, 100 districts, ~300,000 customers
                        # For simple, it defines the number of transactions to run.
duration: "30s"         # e.g., 30s, 1m, 5m
workers: 8              # Base workers (will be overridden by progressive settings)
connections: 16         # Base connections (will be overridden by progressive settings)
summary_interval: "5s"  # Interval for periodic summaries during run

# Progressive scaling configuration - 3 hour test with 6 bands of 30 minutes each
progressive:
  enabled: true
  min_workers: 10
  step_workers: 10
  max_workers: 60
  min_connections: 20
  step_connections: 20
  max_connections: 120
  band_duration: "1800s"         # 30 minutes per band (3 hours total รท 6 bands)
  warmup_time: "60s"             # 1 minute warmup
  cooldown_time: "30s"           # 30 second cooldown
  strategy: "linear"
  export_format: "csv"
  export_path: "./progressive_results"

# PostgreSQL monitoring options
collect_pg_stats: true      # Enable PostgreSQL statistics collection
pg_stats_statements: false  # Enable pg_stat_statements collection (requires extension)

# Connection management options
connection_mode: "persistent"  # "persistent", "transient", or "mixed" (for connection_overhead test)