# Comprehensive pgvector Ingestion Test - Batch Inserts
# Tests batch insert performance with configurable batch size
database:
  type: postgres
  host: "localhost"
  port: 5432
  dbname: "stormdb_vector_test"
  username: "storm_user"
  password: "storm_pwd!123"
  sslmode: "disable"

plugins:
  paths:
    - "./plugins"
    - "./build/plugins"
  files:
    - "./build/plugins/vector_plugin.so"
  auto_load: true

workload: "pgvector_ingestion_batch"
scale: 1000                # Very small for testing
duration: "60s"
workers: 4
connections: 8

test_config:
  dimensions: 256              # Smaller dimensions for faster testing
  similarity_metric: "cosine"
  batch_size: 50               # Smaller batches
  baseline_rows: 1000          # Very small baseline
  precomputed_percentage: 10
